export const movies = [
  // {
  // id: 1,
  //   title: "Lady in the Lake",
  //   prod: "Apple TV+",
  //   dir: "Alma Ha'rel",
  //   dp: "Lachlan Milne, M. Mesa",
  //   img: "#",
  //   link: "#?mute=0",
  // },
  // {
  // id: 2,
  //   title: "Young Woman and the sea",
  //   prod: "Jerry Bruckheimer Films",
  //   dir: "Joachim Ronning",
  //   dp: "Oscar Faura",
  //   img: "#",
  //   link: "#?mute=0",
  // },
  // {
  // id: 3,
  //   title: "Desert Warrior",
  //   prod: "Lightfuse & Gettaway",
  //   dir: "Ruphert Wyatt",
  //   dp: "Guillermo Garza AMC",
  //   img: "../img/desert-warrior.jpg",
  //   link: "#?mute=0",
  // },
  {
    id: 4,
    title: "Elephant",
    prod: "Fine Line Features",
    dir: "Gus Van Sant",
    dp: "Harris Savides",
    img: "../img/elephant.jpg",
    link: "https://www.youtube.com/watch?v=htlsOf3PnGY?mute=0?mute=0",
  },
  {
    id: 5,
    title: "Last Days",
    prod: "HBO Films, Fine Line Feature",
    dir: "Gus Van Sant",
    dp: "Harris Savides",
    img: "../img/lastdays.jpg",
    link: "https://www.youtube.com/watch?v=HFWnZW3esb8?mute=0",
  },
  {
    id: 6,
    title: "Gerry",
    prod: "Miramax",
    dir: "Gus Van Sant",
    dp: "Harris Savides",
    img: "../img/gerry.jpg",
    link: "https://www.youtube.com/watch?v=5LHKhsXvjMo?mute=0",
  },
  {
    id: 7,
    title: "The Road",
    prod: "2929 Productions",
    dir: "John Hillcoat",
    dp: "Javier Aguirresarobe",
    img: "../img/the-road.jpg",
    link: "https://www.youtube.com/watch?v=tloYv8bUAHY?mute=0",
  },
  {
    id: 8,
    title: "Babel",
    prod: "Paramount Vantage",
    dir: "Alejandro G. Inarritu",
    dp: "Rodrigo Prieto",
    img: "../img/babel.jpg",
    link: "https://www.youtube.com/watch?v=yDNa6t-TDrQ?mute=0",
  },
  {
    id: 9,
    title: "Lioness",
    prod: "Paramount +",
    dir: "John Hilcoat, Anthony Byrne",
    dp: "Paul Camerona, Eic Koretz, Nicolas Karakastanis",
    img: "../img/lioness.jpg",
    link: "https://www.youtube.com/watch?v=2sJTSw2qWnQ?mute=0",
  },
  {
    id: 10,
    title: "Victoria Secret - The Tour",
    prod: "24/7 - Pulse",
    dir: "Lola Raban Oliva",
    dp: "Ari Wegner",
    img: "../img/doja.jpg",
    link: "https://www.youtube.com/watch?v=LCE522ImLwo?mute=0",
  },
  {
    id: 11,
    title: "Monster, The Jeffrey Dahmer Story",
    prod: "Ryan Murphy Productions",
    dir: "Paris Barclay",
    dp: "Jason McCormick",
    img: "../img/dahmer.jpeg",
    link: "https://www.youtube.com/watch?v=4549vhvWFo8?mute=0",
  },
  {
    id: 12,
    title: "Tom Clancy's Jack Ryan S2",
    prod: "Genre Artist",
    dir: "Andrew Bernstein",
    dp: "Arnau Valls Colomer",
    img: "../img/jack-r.jpg",
    link: "https://www.youtube.com/watch?v=Un2zXkM-03U?mute=0",
  },
  {
    id: 13,
    title: "Riviera",
    prod: "Archery Pictures",
    dir: "Paul Walker",
    dp: "Philip Kress",
    img: "../img/rivera.jpg",
    link: "https://youtu.be/EKP8tC1oSbw?mute=0",
  },
  {
    id: 14,
    title: "Okja",
    prod: "Netflix",
    dir: "Bong Joon Ho",
    dp: "Darius Kondji ASC",
    img: "../img/okja.jpg",
    link: "https://www.youtube.com/watch?v=AjCebKn4iic?mute=0",
  },
  {
    id: 15,
    title: "Honey Boy",
    prod: "Automatik / Amazon Studios",
    dir: "Alma Har'el",
    dp: "Natasha Braier",
    img: "../img/honeyboy.jpg",
    link: "https://www.youtube.com/watch?v=5RR8WTQzwSk?mute=0",
  },
  {
    id: 16,
    title: "Replicas",
    prod: "Replicas Holdings",
    dir: "Jeffrey Nachmanoff",
    dp: "Checco Varese ASC",
    img: "../img/replicas.jpg",
    link: "https://www.youtube.com/watch?v=ciqeJ7SBRdQ?mute=0",
  },
  {
    id: 17,
    title: "Triple Nine",
    prod: "Worldview Entertainment",
    dir: "John Hillcoat",
    dp: "Nick Karakapsanis",
    img: "../img/triple-9.jpg",
    link: "https://www.youtube.com/watch?v=vOFqiwmnOYE?mute=0",
  },
  {
    id: 18,
    title: "The Games Maker",
    prod: "Pampa Films / Walt Disney",
    dir: "Juan Pablo Buscarini",
    dp: "Roman Osin",
    img: "../img/gamesmaker.jpg",
    link: "https://www.youtube.com/watch?v=F66dsn_NLqo?mute=0",
  },
  {
    id: 19,
    title: "And soon the darkness",
    prod: "Abandon Pictures",
    dir: "Marcos Effron",
    dp: "Gabriel Beristain",
    img: "../img/darkness.jpg",
    link: "https://www.youtube.com/watch?v=GO8BZF_yNBA?mute=0",
  },
  {
    id: 20,
    title: "There be dragons",
    prod: "Independent",
    dir: "Roland Joffe",
    dp: "Gabriel Beristain",
    img: "../img/dragons.jpg",
    link: "https://www.youtube.com/watch?v=kWVy91GzfsU?mute=0",
  },
  {
    id: 21,
    title: "The Informers",
    prod: "Senator Film Produktion",
    dir: "Gregor Jordan",
    dp: "Petra Korner",
    img: "../img/informers.jpg",
    link: "https://www.youtube.com/watch?v=HxkvJkSIOGk?mute=0",
  },
  {
    id: 22,
    title: "Camp Hell",
    prod: "Holedigger Films",
    dir: "George VanBuskirk",
    dp: "Michael McDonough",
    img: "../img/camphell.jpg",
    link: "https://www.youtube.com/watch?v=A5H5KZcCuDw&t=1s?mute=0",
  },
  {
    id: 23,
    title: "The city of your final destination",
    prod: "Merchant Ivory Productions",
    dir: "James Ivory",
    dp: "Javier Aguirresarobe",
    img: "../img/destination.jpg",
    link: "https://www.youtube.com/watch?v=ZZSf79c8lcU?mute=0",
  },
  {
    id: 24,
    title: "El Pasado",
    prod: "HB Films, Oscar Kramer",
    dir: "Hector Babenco",
    dp: "Ricardo Dellarosa",
    img: "../img/pasado.jpg",
    link: "https://www.youtube.com/watch?v=Aj2qrt1oyos&t=23s?mute=0",
  },
  {
    id: 25,
    title: "El Aura",
    prod: "Patagonik Films, Tornasol",
    dir: "Fabian Bielinsky",
    dp: "Franchesco Varesse",
    img: "../img/aura.jpeg",
    link: "https://www.youtube.com/watch?v=aJpAJCBHwjY?mute=0",
  },
  {
    id: 26,
    title: "El Custodio",
    prod: "Rizoma Films, Primer Plano",
    dir: "Rodrigo Moreno",
    dp: "Barbara Alvarez",
    img: "../img/custodio.jpg",
    link: "https://www.youtube.com/watch?v=UKYLsserHMw?mute=0",
  },
  {
    id: 27,
    title: "Blessed by Fire",
    prod: "UN SAM, Canal+, IN CAA",
    dir: "Tristan Bauer",
    dp: "Javier Julia",
    img: "../img/blessedbyfire.jpg",
    link: "https://www.youtube.com/watch?v=c3Pyou7P4DU?mute=0",
  },
  {
    id: 28,
    title: "Water",
    prod: "Bambu, Archipel 35",
    dir: "Veronica Chen",
    dp: "Sabine Lancelin",
    img: "../img/agua.jpg",
    link: "https://www.youtube.com/watch?v=Ln0wI51hpZI?mute=0",
  },
  {
    id: 29,
    title: "Whiskey, Romeo, Zulu",
    prod: "Aquafilms",
    dir: "Enrique Pineyro",
    dp: "Ramiro Chivita",
    img: "../img/whisky.jpg",
    link: "https://www.youtube.com/watch?v=BZWm5ghcrxM?mute=0",
  },
  {
    id: 30,
    title: "The Whore & The Whale",
    prod: "Patagonik, Wanda Vision",
    dir: "Luis Puenzo",
    dp: "Jose Luis Alcaine",
    img: "../img/whorewhale.jpg",
    link: "https://www.youtube.com/watch?v=tW9obud1YOA?mute=0",
  },
  {
    id: 31,
    title: "Nine Queens",
    prod: "Patagonik, Sony Pictures",
    dir: "Fabian Bielinsky",
    dp: "Marcelo Camorino",
    img: "../img/nueve-reinas.jpg",
    link: "https://www.youtube.com/watch?v=P63PyjeDoKk?mute=0",
  },
  {
    id: 32,
    title: "The walking dead - S10",
    prod: "AMC",
    dir: "Greg Nikotero",
    dp: "Duane Manwiller",
    img: "../img/twd.jpg",
    link: "https://www.youtube.com/watch?v=DB8x81nL8B0?mute=0",
  },
  {
    id: 33,
    title: "Operation Finale",
    prod: "MGM",
    dir: "Chris Weitz",
    dp: "Javier Aguirresarobe",
    img: "../img/operacion-f.jpg",
    link: "https://www.youtube.com/watch?v=07Y4_6PD0Z4?mute=0",
  },
  {
    id: 34,
    title: "Beyond Sleep",
    prod: "Key Films",
    dir: "Boudewijn Koole",
    dp: "Melle van Essen",
    img: "../img/beyond-sleep.jpg",
    link: "https://www.youtube.com/watch?v=TtmYZ-mjEX0?mute=0",
  },
];
